env: "local"    # Окружение - local, dev или prod
storage_path: "./storage/storage.db"    # файл, в котором будет храниться наша БД
http_server:    # конфигурация нашего http-сервера
  address: "localhost:8082"
  timeout: 5s   # время на чтение запроса и такое же время на отправку ответа
  idle_timeout: 60s   # время жизни соединения с клиентом